---
deployment:
  tasks:
    - export DEPLOYPATH=/home3/zzflgmfd/excel.bcsrp/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R app $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
    - /bin/cp -R storage $DEPLOYPATH
    - /bin/cp -R sample_import $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp index.php $DEPLOYPATH
    - /bin/cp install.php $DEPLOYPATH
    - /bin/cp cron.php $DEPLOYPATH
    - /bin/cp README_FA.md $DEPLOYPATH
    - /bin/cp INSTALL_CPanel_FA.md $DEPLOYPATH
